---
  version: "3.7"
  services:
    rbmq:
      image: cgerull/rbmq-image:latest
      container_name: rbmq
      hostname: rbmq
      ports:
        - 5672:5672
        - 15672:15672

    rbmq-producer:
      image: cgerull/rbmq-test:1.1.0
      #image: rbmq-test:1.0.0
      environment:
        RBMQ_HOST: rbmq
        RBMQ_QUEUE: docker_queue
        RBMQ_INTERVAL: 1
        MODE: produce
      depends_on:
        - rbmq
 
    rbmq-consumer:
      image: cgerull/rbmq-test:1.1.0
      #image: rbmq-test:1.0.0
      environment:
        RBMQ_HOST: rbmq
        RBMQ_QUEUE: docker_queue
        MODE: consume
      depends_on:
        - rbmq
